/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChartTitle: typeof import('./src/components/charts/ChartTitle.vue')['default']
    DragWrapper: typeof import('./src/components/dragChart/DragWrapper.vue')['default']
    DropArea: typeof import('./src/components/dragChart/DropArea.vue')['default']
    EchartComponent: typeof import('./src/components/charts/EchartComponent.vue')['default']
    EditorTinymce: typeof import('./src/components/EditorTinymce.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    EmptyRouterView: typeof import('./src/components/EmptyRouterView.vue')['default']
    FileDownload: typeof import('./src/components/download/FileDownload.vue')['default']
    GridCollapse: typeof import('./src/components/GridCollapse.vue')['default']
    ListPagination: typeof import('./src/components/ListPagination.vue')['default']
    NumberChart: typeof import('./src/components/charts/NumberChart.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Table: typeof import('./src/components/table/index.vue')['default']
  }
}
